.for_development:
  environment:
    name: development
  variables:
    DOCKER_IMAGE_TAG: latest
  only:
    - main

.for_release:
  environment:
    name: release

.build:
  stage: build
  services:
    - docker:dind
  script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - docker pull ${CI_REGISTRY_IMAGE}:${DOCKER_IMAGE_TAG} || true .
    - docker build .
    - docker push ${CI_REGISTRY_IMAGE}:${DOCKER_IMAGE_TAG}

development:publish:
  extends:
    - .build
    - .for_development

.prepare_release:
  extends: .build
  stage: build
  before_script:
    - DOCKER_IMAGE_TAG=${CI_COMMIT_TAG}
    
release:publish:
  extends:
    - .prepare_release
    - .for_release
  rules:
    - if: $BY_TRIGGER == 'true'