# name of workflow
name: Main Workflow - Build docker and push to docker hub

# trigger
on:
  push:
    branches:
      - main

jobs:
  
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v4
      
      - name: login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: glendmaatita/own-your-stack:latest

  